<?php

declare(strict_types=1);

namespace phpGPX\Tests\Integration;

use DateTime;
use phpGPX\Models\Bounds;
use phpGPX\Models\Copyright;
use phpGPX\Models\Email;
use phpGPX\Models\GpxFile;
use phpGPX\Models\Link;
use phpGPX\Models\Point;
use phpGPX\Models\Route;
use phpGPX\phpGPX;
use phpGPX\Tests\Support\Factories\MetadataFactory;
use phpGPX\Tests\Support\Factories\PointFactory;
use phpGPX\Tests\Support\Factories\TrackFactory;
use phpGPX\Tests\Support\TestCase;
use phpGPX\Tests\Support\XsdValidator;

/**
 * Integration tests for validating generated GPX files against the official GPX 1.1 XSD schema.
 *
 * These tests ensure that all GPX files generated by the library are fully compliant
 * with the GPX 1.1 specification from topografix.com.
 *
 * Tests Requirements: All (GPX 1.1 Schema Compliance)
 */
final class XsdValidationTest extends TestCase
{
	/**
	 * Test that a minimal GPX file validates against the XSD.
	 *
	 * Requirements: 12.1, 12.2, 12.3
	 */
	public function test_minimal_gpx_file_validates_against_xsd(): void
	{
		// Arrange - Create minimal GPX file with only required elements
		$gpxFile = new GpxFile('phpGPX XSD Test');

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'Minimal GPX file should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with waypoints validates against the XSD.
	 *
	 * Requirements: 1.1, 1.2, 1.3, 1.4, 1.5
	 */
	public function test_gpx_file_with_waypoints_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with waypoints
		$gpxFile = new GpxFile('phpGPX Waypoint Test');

		// Add waypoints with various properties
		$waypoint1 = PointFactory::create([
			'pointType' => Point::WAYPOINT,
			'latitude' => 54.9328621088893,
			'longitude' => 9.860624216140083,
			'elevation' => 42.5,
			'name' => 'Test Waypoint 1',
			'description' => 'A test waypoint',
		]);
		$gpxFile->waypoints[] = $waypoint1;

		$waypoint2 = PointFactory::create([
			'pointType' => Point::WAYPOINT,
			'latitude' => -45.5,
			'longitude' => 170.25,
			'name' => 'Test Waypoint 2',
		]);
		$gpxFile->waypoints[] = $waypoint2;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with waypoints should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with tracks validates against the XSD.
	 *
	 * Requirements: 1.1, 1.2, 1.3, 1.4, 1.5
	 */
	public function test_gpx_file_with_tracks_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with tracks
		$gpxFile = new GpxFile('phpGPX Track Test');

		// Add track with multiple segments
		$track = TrackFactory::createWithSegments(2, 3);
		$track->name = 'Test Track';
		$track->description = 'A test track with multiple segments';
		$gpxFile->tracks[] = $track;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with tracks should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with routes validates against the XSD.
	 *
	 * Requirements: 1.1, 1.2, 1.3, 1.4, 1.5
	 */
	public function test_gpx_file_with_routes_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with routes
		$gpxFile = new GpxFile('phpGPX Route Test');

		// Create route with points
		$route = new Route();
		$route->name = 'Test Route';
		$route->description = 'A test route';

		$routePoint1 = PointFactory::create([
			'pointType' => Point::ROUTEPOINT,
			'latitude' => 54.9328621088893,
			'longitude' => 9.860624216140083,
			'name' => 'Route Point 1',
		]);
		$route->points[] = $routePoint1;

		$routePoint2 = PointFactory::create([
			'pointType' => Point::ROUTEPOINT,
			'latitude' => 54.9428621088893,
			'longitude' => 9.870624216140083,
			'name' => 'Route Point 2',
		]);
		$route->points[] = $routePoint2;

		$gpxFile->routes[] = $route;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with routes should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with metadata validates against the XSD.
	 *
	 * Requirements: 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.1, 3.2, 3.3, 4.1, 4.2, 4.3
	 */
	public function test_gpx_file_with_metadata_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with comprehensive metadata
		$gpxFile = new GpxFile('phpGPX Metadata Test');

		$metadata = MetadataFactory::create([
			'name' => 'Test GPX with Metadata',
			'description' => 'Testing metadata validation',
			'time' => new DateTime('2024-01-15T10:30:00Z'),
			'keywords' => 'test, validation, xsd',
		]);

		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with metadata should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with bounds validates against the XSD.
	 *
	 * Requirements: 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7
	 */
	public function test_gpx_file_with_bounds_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with bounds in metadata
		$gpxFile = new GpxFile('phpGPX Bounds Test');

		$metadata = MetadataFactory::create([
			'name' => 'Test GPX with Bounds',
		]);

		// Add bounds with all four required coordinates
		$metadata->bounds = new Bounds(
			minLatitude: 54.0,
			minLongitude: 9.0,
			maxLatitude: 55.0,
			maxLongitude: 10.0,
		);

		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with bounds should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with links validates against the XSD.
	 *
	 * Requirements: 3.1, 3.2, 3.3
	 */
	public function test_gpx_file_with_links_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with links
		$gpxFile = new GpxFile('phpGPX Link Test');

		$metadata = MetadataFactory::create([
			'name' => 'Test GPX with Links',
		]);

		// Add link with required href
		$link = new Link('https://example.com/gpx-test');
		$link->text = 'Example Link';
		$link->type = 'text/html';
		$metadata->links[] = $link;

		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with links should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with copyright validates against the XSD.
	 *
	 * Requirements: 4.1, 4.2, 4.3
	 */
	public function test_gpx_file_with_copyright_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with copyright
		$gpxFile = new GpxFile('phpGPX Copyright Test');

		$metadata = MetadataFactory::create([
			'name' => 'Test GPX with Copyright',
		]);

		// Add copyright with required author
		$copyright = new Copyright('Test Author');
		$copyright->year = '2024';
		$copyright->license = 'https://creativecommons.org/licenses/by/4.0/';
		$metadata->copyright = $copyright;

		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with copyright should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a GPX file with email validates against the XSD.
	 *
	 * Requirements: 5.1, 5.2, 5.3
	 */
	public function test_gpx_file_with_email_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with email in author
		$gpxFile = new GpxFile('phpGPX Email Test');

		$metadata = MetadataFactory::create([
			'name' => 'Test GPX with Email',
		]);

		// Add author with email
		$metadata->author = new \phpGPX\Models\Person();
		$metadata->author->name = 'Test Author';
		$metadata->author->email = new Email('test', 'example.com');

		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with email should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that a comprehensive GPX file with all elements validates against the XSD.
	 *
	 * Requirements: All
	 */
	public function test_comprehensive_gpx_file_validates_against_xsd(): void
	{
		// Arrange - Create comprehensive GPX file with all element types
		$gpxFile = new GpxFile('phpGPX Comprehensive Test');

		// Add comprehensive metadata
		$metadata = MetadataFactory::create([
			'name' => 'Comprehensive Test GPX',
			'description' => 'A GPX file with all possible elements',
			'time' => new DateTime('2024-01-15T10:30:00Z'),
			'keywords' => 'comprehensive, test, validation',
		]);

		// Add bounds
		$metadata->bounds = new Bounds(
			minLatitude: 54.0,
			minLongitude: 9.0,
			maxLatitude: 55.0,
			maxLongitude: 10.0,
		);

		// Add link
		$metadata->links[] = new Link('https://example.com/comprehensive-test');

		// Add copyright
		$metadata->copyright = new Copyright('Comprehensive Test Author');
		$metadata->copyright->year = '2024';

		// Add author with email
		$metadata->author = new \phpGPX\Models\Person();
		$metadata->author->name = 'Test Author';
		$metadata->author->email = new Email('author', 'example.com');

		$gpxFile->metadata = $metadata;

		// Add waypoints
		$waypoint = PointFactory::create([
			'pointType' => Point::WAYPOINT,
			'latitude' => 54.9328621088893,
			'longitude' => 9.860624216140083,
			'elevation' => 42.5,
			'name' => 'Comprehensive Waypoint',
			'description' => 'A waypoint with all properties',
		]);
		$gpxFile->waypoints[] = $waypoint;

		// Add track
		$track = TrackFactory::createWithSegments(2, 3);
		$track->name = 'Comprehensive Track';
		$track->description = 'A track with multiple segments';
		$gpxFile->tracks[] = $track;

		// Add route
		$route = new Route();
		$route->name = 'Comprehensive Route';
		$route->description = 'A route with multiple points';
		$route->points[] = PointFactory::create(['pointType' => Point::ROUTEPOINT]);
		$route->points[] = PointFactory::create(['pointType' => Point::ROUTEPOINT]);
		$gpxFile->routes[] = $route;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'Comprehensive GPX file should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that existing fixture GPX files validate against the XSD.
	 *
	 * Requirements: All
	 */
	public function test_fixture_gpx_files_validate_against_xsd(): void
	{
		$fixtureFiles = [
			'minimal-gpx.gpx',
			'complete-gpx.gpx',
			'gps-track.gpx',
			'route.gpx',
			'track-with-extensions.gpx',
		];

		foreach ($fixtureFiles as $filename) {
			// Arrange - Load fixture file
			$gpx = new phpGPX();
			$gpxFile = $gpx->load($this->getFixturePath($filename));

			// Act - Generate XML from parsed file
			$xml = $gpxFile->toXML()->saveXML();

			// Assert - Validate against XSD
			$result = XsdValidator::validate($xml);

			$this->assertTrue(
				$result['valid'],
				"Fixture file '{$filename}' should validate against XSD. Errors: " . implode('; ', $result['errors']),
			);
		}
	}

	/**
	 * Test that GPX files with boundary coordinate values validate against the XSD.
	 *
	 * Requirements: 1.4, 1.5, 2.4, 2.5
	 */
	public function test_gpx_file_with_boundary_coordinates_validates_against_xsd(): void
	{
		// Arrange - Create GPX file with boundary coordinate values
		$gpxFile = new GpxFile('phpGPX Boundary Test');

		// Add waypoints at coordinate boundaries
		$waypoints = [
			// Latitude boundaries
			PointFactory::create(['pointType' => Point::WAYPOINT, 'latitude' => -90.0, 'longitude' => 0.0]),
			PointFactory::create(['pointType' => Point::WAYPOINT, 'latitude' => 90.0, 'longitude' => 0.0]),
			// Longitude boundaries
			PointFactory::create(['pointType' => Point::WAYPOINT, 'latitude' => 0.0, 'longitude' => -180.0]),
			PointFactory::create(['pointType' => Point::WAYPOINT, 'latitude' => 0.0, 'longitude' => 179.999999]),
		];

		foreach ($waypoints as $waypoint) {
			$gpxFile->waypoints[] = $waypoint;
		}

		// Add bounds at boundaries
		$metadata = MetadataFactory::create(['name' => 'Boundary Test']);
		$metadata->bounds = new Bounds(
			minLatitude: -90.0,
			minLongitude: -180.0,
			maxLatitude: 90.0,
			maxLongitude: 179.999999,
		);
		$gpxFile->metadata = $metadata;

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with boundary coordinates should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that GPX version 1.1 is always present in generated files.
	 *
	 * Requirements: 12.2
	 */
	public function test_gpx_version_1_1_is_present_and_validates(): void
	{
		// Arrange
		$gpxFile = new GpxFile('phpGPX Version Test');

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Check version attribute
		$this->assertStringContainsString('version="1.1"', $xml, 'GPX version 1.1 should be present');

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with version 1.1 should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}

	/**
	 * Test that GPX creator attribute is always present in generated files.
	 *
	 * Requirements: 12.1, 12.3, 12.4
	 */
	public function test_gpx_creator_is_present_and_validates(): void
	{
		// Arrange
		$gpxFile = new GpxFile('Test Creator Application v1.0');

		// Act - Generate XML
		$xml = $gpxFile->toXML()->saveXML();

		// Assert - Check creator attribute
		$this->assertStringContainsString('creator="Test Creator Application v1.0"', $xml, 'GPX creator should be present');

		// Assert - Validate against XSD
		$result = XsdValidator::validate($xml);

		$this->assertTrue(
			$result['valid'],
			'GPX file with creator should validate against XSD. Errors: ' . implode('; ', $result['errors']),
		);
	}
}
